# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - "Makefile"
      - ".github/workflows/main.yaml"
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - "Makefile"
      - ".github/workflows/main.yaml"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ERC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          kicad: 5
          dir: "Export"
          skip: run_drc
          targets: __NONE__
      - name: Retrieve results
        uses: actions/upload-artifact@v2
        with:
          name: ERC_Output
          path: Export
  DRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run DRC
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          kicad: 5
          dir: "Export"
          skip: run_erc
          targets: __NONE__
      - name: Retrieve results
        uses: actions/upload-artifact@v1
        with:
          name: DRC_Output
          path: Export
  default:
    name: "Main"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: config.kibot.yaml
      - name: Commits files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add -f ./Export ./Datasheets ./Gerber ./View
          git commit -m "[CI] Auto-release exports files"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

#- name: upload results
#uses: actions/upload-artifact@v2
#with:
#name: default
#path: .
